"""Adapter components for the QQ Official Bot API."""

from app.adapters.qq_official.auth import (
    QQAccessToken,
    QQOfficialAuthClient,
    QQOfficialAuthConfigurationError,
    QQOfficialAuthError,
    QQOfficialAuthHTTPError,
    QQOfficialAuthResponseError,
    QQOfficialAuthTransportError,
)
from app.adapters.qq_official.gateway import (
    GROUP_AND_C2C_EVENT_INTENT,
    QQGatewayDispatch,
    QQGatewayInfo,
    QQGatewayReady,
    QQOfficialGatewayClient,
    QQOfficialGatewayError,
    QQOfficialGatewayHTTPError,
    QQOfficialGatewayProtocolError,
    QQOfficialGatewayResponseError,
    QQOfficialGatewayTransportError,
)
from app.adapters.qq_official.message_api import (
    QQOfficialMessageAPIAuthenticationError,
    QQOfficialGroupMessageSendResult,
    QQOfficialGroupMessageSender,
    QQOfficialMessageAPIError,
    QQOfficialMessageAPIHTTPError,
    QQOfficialMessageAPINotFoundError,
    QQOfficialMessageAPIPermissionError,
    QQOfficialMessageAPIRequestError,
    QQOfficialMessageAPIRateLimitError,
    QQOfficialMessageAPIResponseError,
    QQOfficialMessageAPIServerError,
    QQOfficialMessageAPITimeoutError,
    QQOfficialMessageAPITransportError,
)

__all__ = [
    "QQAccessToken",
    "QQOfficialAuthClient",
    "QQOfficialAuthConfigurationError",
    "QQOfficialAuthError",
    "QQOfficialAuthHTTPError",
    "QQOfficialAuthResponseError",
    "QQOfficialAuthTransportError",
    "GROUP_AND_C2C_EVENT_INTENT",
    "QQGatewayDispatch",
    "QQGatewayInfo",
    "QQGatewayReady",
    "QQOfficialGatewayClient",
    "QQOfficialGatewayError",
    "QQOfficialGatewayHTTPError",
    "QQOfficialGatewayProtocolError",
    "QQOfficialGatewayResponseError",
    "QQOfficialGatewayTransportError",
    "QQOfficialGroupMessageSendResult",
    "QQOfficialGroupMessageSender",
    "QQOfficialMessageAPIAuthenticationError",
    "QQOfficialMessageAPIError",
    "QQOfficialMessageAPIHTTPError",
    "QQOfficialMessageAPINotFoundError",
    "QQOfficialMessageAPIPermissionError",
    "QQOfficialMessageAPIRequestError",
    "QQOfficialMessageAPIRateLimitError",
    "QQOfficialMessageAPIResponseError",
    "QQOfficialMessageAPIServerError",
    "QQOfficialMessageAPITimeoutError",
    "QQOfficialMessageAPITransportError",
]
